# **Computational Drug Discovery [Part 1] Download Bioactivity Data**

Chanin Nantasenamat

[*'Data Professor' YouTube channel*](http://youtube.com/dataprofessor)

In this Jupyter notebook, we will be building a real-life **data science project** that you can include in your **data science portfolio**. Particularly, we will be building a machine learning model using the ChEMBL bioactivity data.

---

## **ChEMBL Database**

The [*ChEMBL Database*](https://www.ebi.ac.uk/chembl/) is a database that contains curated bioactivity data of more than 2 million compounds. It is compiled from more than 76,000 documents, 1.2 million assays and the data spans 13,000 targets and 1,800 cells and 33,000 indications.
[Data as of March 25, 2020; ChEMBL version 26].

## **Installing libraries**

Install the ChEMBL web service package so that we can retrieve bioactivity data from the ChEMBL Database.

## **Importing libraries**

In [1]:
! pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.3-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.13/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.19)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.7.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.2.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.11.7)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.13/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.16.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 1.8 MB/s eta 0:00:00
Downloading requests_cache-1.3.3-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.8/70.8 kB 5.4 MB/s eta 0:00:00
Downloading cattrs-26.2.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.8/74.8 kB 5.6 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.2.0 chembl_webresource_client-0.10.9 requests-cache-1.3.3 url-normalize-3.0.0

In [8]:
# Import necessary libraries
import pandas as pd
from chembl_webresource_client.new_client import new_client

## **Search for Target protein**

### **Target search for coronavirus**

In [12]:
# Target search for coronavirus
target = new_client.target
target_query = target.search('coronavirus')
targets = pd.DataFrame.from_dict(target_query)
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Coronavirus,Coronavirus,17.0,False,CHEMBL613732,[],ORGANISM,11119
1,[],Feline coronavirus,Feline coronavirus,14.0,False,CHEMBL612744,[],ORGANISM,12663
2,[],Murine coronavirus,Murine coronavirus,14.0,False,CHEMBL5209664,[],ORGANISM,694005
3,[],Canine coronavirus,Canine coronavirus,14.0,False,CHEMBL5291668,[],ORGANISM,11153
4,[],Bovine coronavirus,Bovine coronavirus,14.0,False,CHEMBL6066646,[],ORGANISM,11128
5,[],Human coronavirus 229E,Human coronavirus 229E,13.0,False,CHEMBL613837,[],ORGANISM,11137
6,[],Human coronavirus OC43,Human coronavirus OC43,13.0,False,CHEMBL5209665,[],ORGANISM,31631
7,[],unidentified human coronavirus,unidentified human coronavirus,13.0,False,CHEMBL6195448,[],ORGANISM,694448
8,[],Human coronavirus NL63,Human coronavirus NL63,13.0,False,CHEMBL6195756,[],ORGANISM,277944
9,[],Middle East respiratory syndrome-related coron...,Middle East respiratory syndrome-related coron...,9.0,False,CHEMBL4296578,[],ORGANISM,1335626
10,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,5.0,False,CHEMBL3927,"[{'accession': 'P0C6U8', 'component_descriptio...",SINGLE PROTEIN,694009
11,[],Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1ab,4.0,False,CHEMBL5118,"[{'accession': 'P0C6X7', 'component_descriptio...",SINGLE PROTEIN,694009
12,[],Severe acute respiratory syndrome coronavirus 2,Replicase polyprotein 1ab,4.0,False,CHEMBL4523582,"[{'accession': 'P0DTD1', 'component_descriptio...",SINGLE PROTEIN,2697049
13,[],Severe acute respiratory syndrome coronavirus 2,Protein cereblon/Replicase polyprotein 1ab,4.0,False,CHEMBL6067603,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049
14,[],Severe acute respiratory syndrome coronavirus 2,von Hippel-Lindau disease tumor suppressor-SAR...,4.0,False,CHEMBL6067604,"[{'accession': 'P40337', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049

### **Select and retrieve bioactivity data for *SARS coronavirus 3C-like proteinase* (tenth entry)**

We will assign the tenth entry (which corresponds to the target protein, *coronavirus 3C-like proteinase*) to the ***selected_target*** variable

In [15]:
selected_target = targets.target_chembl_id[10]
selected_target

'CHEMBL3927'

Here, we will retrieve only bioactivity data for *coronavirus 3C-like proteinase* (CHEMBL3927) that are reported as IC$_{50}$ values in nM (nanomolar) unit.

In [16]:
activity = new_client.activity
res = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [17]:
df = pd.DataFrame.from_dict(res)

In [18]:
df.head(3)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.5

In [19]:
df.standard_type.unique()

array(['IC50'], dtype=object)

Finally we will save the resulting bioactivity data to a CSV file **bioactivity_data.csv**.

In [20]:
df.to_csv('bioactivity_data.csv', index=False)

## **Copying files to Google Drive**

Firstly, we need to mount the Google Drive into Colab so that we can have access to our Google adrive from within Colab.

In [26]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

Next, we create a **data** folder in our **Colab Notebooks** folder on Google Drive.

In [30]:
! ls '/content/gdrive/My Drive/Colab Notebooks/'

 Bio-informatics.ipynb	 MNIST.ipynb	       Test.ipynb
 data			 PeBusePenalty.ipynb  'Text hyperbolic embedding.ipynb'
 data2			 Sphere.ipynb	       Untitled

In [27]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data2"

mkdir: cannot create directory ‘/content/gdrive/My Drive/Colab Notebooks/data2’: File exists

In [28]:
! cp bioactivity_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [29]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

-rw------- 1 root root 156586 Sep 10 04:19 '/content/gdrive/My Drive/Colab Notebooks/data'

Let's see the CSV files that we have so far.

In [31]:
! ls

bioactivity_data.csv  gdrive  sample_data

Taking a glimpse of the **bioactivity_data.csv** file that we've just created.

In [32]:
! head bioactivity_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,modality,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '18.28', 'le': '0.33', 'lle': '3.25', 'sei': '5.90'}",,CHEMBL187579,,CHEMBL187579,5.14,0,http://www.openphacts.org/units/Nanomolar,384103,=,1,1,=,,IC50,nM,,7200.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,7.2
,,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '12.10', 'le': '0.33', 'lle': '1.22', 'sei': '13.45'}",,CHEMBL188487,,CHEMBL188487,5.03,0,http://www.openphacts.org/units/Nanomolar,383984,=,1,1,=,,IC50,nM,,9400.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,9.4
,,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease) at 20 uM,B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '11.56', 'le': '0.29', 'lle': '2.21', 'sei': '8.72'}",,CHEMBL185698,,CHEMBL185698,4.87,0,http://www.openphacts.org/units/Nanomolar,384106,=,1,1,=,,IC50,nM,,13500.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,13.5
,,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.64', 'le': '0.32', 'lle': '1.25', 'sei': '13.06'}",,CHEMBL426082,,CHEMBL426082,4.88,0,http://www.openphacts.org/units/Nanomolar,384075,=,1,1,=,,IC50,nM,,13110.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,13.11
,,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.84', 'le': '0.32', 'lle': '2.16', 'sei': '7.08'}",,CHEMBL187717,,CHEMBL187717,5.70,0,http://www.openphacts.org/units/Nanomolar,384234,=,1,1,=,,IC50,nM,,2000.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,2.0
,,1481068,[],CHEMBL828143,In vitro inhibitory concentration SARS coronavirus main protease (SARS CoV 3C-like protease) ,B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c(Br)cccc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '16.14', 'le': '0.37', 'lle': '1.62', 'sei': '16.07'}",,CHEMBL365134,,CHEMBL365134,6.01,0,http://www.openphacts.org/units/Nanomolar,384081,=,1,1,=,,IC50,nM,,980.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,0.98
,,1481088,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(F)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '17.08', 'le': '0.33', 'lle': '1.55', 'sei': '14.22'}",,CHEMBL187598,,CHEMBL187598,5.32,0,http://www.openphacts.org/units/Nanomolar,384303,=,1,1,=,,IC50,nM,,4820.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,4.82
,,1481089,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(I)cc21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '14.36', 'le': '0.37', 'lle': '1.78', 'sei': '16.11'}",,CHEMBL190743,,CHEMBL190743,6.02,0,http://www.openphacts.org/units/Nanomolar,384329,=,1,1,=,,IC50,nM,,950.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,0.95
,,1481093,[],CHEMBL829584,In vitro inhibitory concentration against SARS coronavirus main protease (SARS CoV 3C-like protease),B,,,BAO_0000190,BAO_0000357,single protein format,O=C1C(=O)N(Cc2cc3ccccc3s2)c2cccc(Cl)c21,,,CHEMBL1139624,Bioorg Med Chem Lett,2005,"{'bei': '15.10', 'le': '0.31', 'lle': '0.67', 'sei': '13.24'}",,CHEMBL365469,,CHEMBL365469,4.95,0,http://www.openphacts.org/units/Nanomolar,384283,=,1,1,=,,IC50,nM,,11200.0,CHEMBL3927,Severe acute respiratory syndrome-related coronavirus,Replicase polyprotein 1a,694009,,,IC50,uM,UO_0000065,,11.2

## **Handling missing data**
If any compounds has missing value for the **standard_value** column then drop it

In [33]:
df2 = df[df.standard_value.notna()]
df2

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,1480935,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,7.2
1,None,None,1480936,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,9.4
2,None,None,1481061,[],CHEMBL830868,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.5
3,None,None,1481065,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,13.11
4,None,None,1481066,[],CHEMBL829584,In vitro inhibitory concentration against SARS...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992024,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,48.0
260,"{'action_type': 'INHIBITOR', 'description': 'N...",None,25992025,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL5550822,Inhibition of SARS-CoV-1 main protease using D...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,20.0
261,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29103838,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6086440,Inhibition of SARS-CoV MPro using Dabcyl-KTSAV...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,0.053
262,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29103839,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6086440,Inhibition of SARS-CoV MPro using Dabcyl-KTSAV...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,uM,UO_0000065,None,0.04
263,"{'action_type': 'INHIBITOR', 'description': 'N...",None,29103840,"[{'comments': None, 'relation': '=', 'result_f...",CHEMBL6086440,Inhibition of SARS-CoV MPro using Dabcyl-KTSAV...,B,None,None,BAO_0000190,...,Severe acute respiratory syndrome-related coro...,Replicase polyprotein 1a,694009,None,None,IC50,nM,UO_0000065,None,170.0

Warning: Total number of columns (47) exceeds max_columns (20) limiting to first (20) columns.

Apparently, for this dataset there is no missing data. But we can use the above code cell for bioactivity data of other target protein.

## **Data pre-processing of the bioactivity data**

### **Labeling compounds as either being active, inactive or intermediate**
The bioactivity data is in the IC50 unit. Compounds having values of less than 1000 nM will be considered to be **active** while those greater than 10,000 nM will be considered to be **inactive**. As for those values in between 1,000 and 10,000 nM will be referred to as **intermediate**.

In [34]:
df2[['canonical_smiles', 'standard_type', 'standard_value', 'standard_units']].head()

,canonical_smiles,standard_type,standard_value,standard_units
0,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,IC50,7200.0,nM
1,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,IC50,9400.0,nM
2,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,IC50,13500.0,nM
3,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,IC50,13110.0,nM
4,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],IC50,2000.0,nM

In [35]:
bioactivity_class = []
for i in df2.standard_value:
  if float(i) >= 10000:
    bioactivity_class.append("inactive")
  elif float(i) <= 1000:
    bioactivity_class.append("active")
  else:
    bioactivity_class.append("intermediate")

### **Iterate the *molecule_chembl_id* to a list**

In [36]:
mol_cid = []
for i in df2.molecule_chembl_id:
  mol_cid.append(i)

In [38]:
mol_cid

['CHEMBL187579',
 'CHEMBL188487',
 'CHEMBL185698',
 'CHEMBL426082',
 'CHEMBL187717',
 'CHEMBL365134',
 'CHEMBL187598',
 'CHEMBL190743',
 'CHEMBL365469',
 'CHEMBL188983',
 'CHEMBL191575',
 'CHEMBL370923',
 'CHEMBL194398',
 'CHEMBL196635',
 'CHEMBL209287',
 'CHEMBL358279',
 'CHEMBL348660',
 'CHEMBL379727',
 'CHEMBL210525',
 'CHEMBL148483',
 'CHEMBL383725',
 'CHEMBL118596',
 'CHEMBL208732',
 'CHEMBL208732',
 'CHEMBL210146',
 'CHEMBL210146',
 'CHEMBL207458',
 'CHEMBL207458',
 'CHEMBL207484',
 'CHEMBL207484',
 'CHEMBL207207',
 'CHEMBL207207',
 'CHEMBL210487',
 'CHEMBL210487',
 'CHEMBL380470',
 'CHEMBL380470',
 'CHEMBL210612',
 'CHEMBL210612',
 'CHEMBL209667',
 'CHEMBL209667',
 'CHEMBL210097',
 'CHEMBL210097',
 'CHEMBL378674',
 'CHEMBL378674',
 'CHEMBL210216',
 'CHEMBL210216',
 'CHEMBL210195',
 'CHEMBL210195',
 'CHEMBL210437',
 'CHEMBL210437',
 'CHEMBL378677',
 'CHEMBL378677',
 'CHEMBL210972',
 'CHEMBL210972',
 'CHEMBL210145',
 'CHEMBL210145',
 'CHEMBL377225',
 'CHEMBL377225',
 'CHEMBL210823',
 'CHEMBL210823',
 'CHEMBL207381',
 'CHEMBL207381',
 'CHEMBL210511',
 'CHEMBL210511',
 'CHEMBL210632',
 'CHEMBL210632',
 'CHEMBL210497',
 'CHEMBL210497',
 'CHEMBL208584',
 'CHEMBL208584',
 'CHEMBL208763',
 'CHEMBL208763',
 'CHEMBL209227',
 'CHEMBL209227',
 'CHEMBL210092',
 'CHEMBL210092',
 'CHEMBL377150',
 'CHEMBL377150',
 'CHEMBL212454',
 'CHEMBL213581',
 'CHEMBL380403',
 'CHEMBL212504',
 'CHEMBL211969',
 'CHEMBL384739',
 'CHEMBL215732',
 'CHEMBL212240',
 'CHEMBL377253',
 'CHEMBL215397',
 'CHEMBL378342',
 'CHEMBL379642',
 'CHEMBL427404',
 'CHEMBL212190',
 'CHEMBL378700',
 'CHEMBL212019',
 'CHEMBL212399',
 'CHEMBL215733',
 'CHEMBL375130',
 'CHEMBL214372',
 'CHEMBL212218',
 'CHEMBL222840',
 'CHEMBL222769',
 'CHEMBL222735',
 'CHEMBL222628',
 'CHEMBL222893',
 'CHEMBL225515',
 'CHEMBL222234',
 'CHEMBL426898',
 'CHEMBL269277',
 'CHEMBL1448',
 'CHEMBL140',
 'CHEMBL395263',
 'CHEMBL242011',
 'CHEMBL431525',
 'CHEMBL258787',
 'CHEMBL2372143',
 'CHEMBL259622',
 'CHEMBL261189',
 'CHEMBL265704',
 'CHEMBL261402',
 'CHEMBL258581',
 'CHEMBL409422',
 'CHEMBL2372143',
 'CHEMBL2372143',
 'CHEMBL2372143',
 'CHEMBL2372143',
 'CHEMBL2372143',
 'CHEMBL523052',
 'CHEMBL495231',
 'CHEMBL468553',
 'CHEMBL222234',
 'CHEMBL1082811',
 'CHEMBL1082812',
 'CHEMBL1083123',
 'CHEMBL1083124',
 'CHEMBL1082714',
 'CHEMBL1082715',
 'CHEMBL327313',
 'CHEMBL1083958',
 'CHEMBL1083959',
 'CHEMBL1083286',
 'CHEMBL1082332',
 'CHEMBL1086234',
 'CHEMBL1082333',
 'CHEMBL1082334',
 'CHEMBL1084478',
 'CHEMBL1084479',
 'CHEMBL1084480',
 'CHEMBL1084481',
 'CHEMBL187266',
 'CHEMBL215254',
 'CHEMBL2146517',
 'CHEMBL187460',
 'CHEMBL363535',
 'CHEMBL227075',
 'CHEMBL45830',
 'CHEMBL187266',
 'CHEMBL215254',
 'CHEMBL2146517',
 'CHEMBL187460',
 'CHEMBL363535',
 'CHEMBL227075',
 'CHEMBL45830',
 'CHEMBL215254',
 'CHEMBL187460',
 'CHEMBL363535',
 'CHEMBL227075',
 'CHEMBL45830',
 'CHEMBL187266',
 'CHEMBL215254',
 'CHEMBL2146517',
 'CHEMBL187460',
 'CHEMBL363535',
 'CHEMBL227075',
 'CHEMBL45830',
 'CHEMBL18786',
 'CHEMBL2311740',
 'CHEMBL2311736',
 'CHEMBL2311734',
 'CHEMBL2311733',
 'CHEMBL2311732',
 'CHEMBL2311731',
 'CHEMBL2311730',
 'CHEMBL2311729',
 'CHEMBL2311727',
 'CHEMBL2311726',
 'CHEMBL2311709',
 'CHEMBL2311705',
 'CHEMBL2311700',
 'CHEMBL2311695',
 'CHEMBL2311694',
 'CHEMBL1405735',
 'CHEMBL2311693',
 'CHEMBL2311692',
 'CHEMBL2311691',
 'CHEMBL2397338',
 'CHEMBL2402686',
 'CHEMBL2402685',
 'CHEMBL2402680',
 'CHEMBL2402508',
 'CHEMBL2402501',
 'CHEMBL18786',
 'CHEMBL1929019',
 'CHEMBL2402692',
 'CHEMBL2402691',
 'CHEMBL406516',
 'CHEMBL2442082',
 'CHEMBL2442053',
 'CHEMBL2442054',
 'CHEMBL2442055',
 'CHEMBL2442056',
 'CHEMBL2442057',
 'CHEMBL2442058',
 'CHEMBL2442059',
 'CHEMBL2442061',
 'CHEMBL2442062',
 'CHEMBL2442063',
 'CHEMBL2442064',
 'CHEMBL2442065',
 'CHEMBL2442066',
 'CHEMBL2442067',
 'CHEMBL2442069',
 'CHEMBL2442073',
 'CHEMBL2442074',
 'CHEMBL2442075',
 'CHEMBL2442076',
 'CHEMBL2442077',
 'CHEMBL2442078',
 'CHEMBL2442079',
 'CHEMBL2440138',
 'CHEMBL2442080',
 'CHEMBL2311693',
 'CHEMBL18786',
 'CHEMBL2311692',
 'CHEMBL2442081',
 'CHEMBL4465864',
 'CHEMBL4532437',
 'CHEMBL4437284',
 'CHEMBL4459894',
 'CHEMBL18786',
 'CHEMBL4590273',
 'CHEMBL4590273',
 'CHEMBL5436771',
 'CHEMBL2365410',
 'CHEMBL5436771',
 'CHEMBL2365410',
 'CHEMBL5560356',
 'CHEMBL4850298',
 'CHEMBL3427166',
 'CHEMBL5593485',
 'CHEMBL5195325',
 'CHEMBL5564834',
 'CHEMBL218394',
 'CHEMBL2311740',
 'CHEMBL5563508',
 'CHEMBL5595277',
 'CHEMBL5570210',
 'CHEMBL5565685',
 'CHEMBL5565858',
 'CHEMBL4802135',
 'CHEMBL4796938',
 'CHEMBL4764751',
 'CHEMBL2022564']

### **Iterate *canonical_smiles* to a list**

In [39]:
canonical_smiles = []
for i in df2.canonical_smiles:
  canonical_smiles.append(i)

In [40]:
canonical_smiles

['Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21',
 'O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21',
 'O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21',
 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21',
 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-]',
 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2c(Br)cccc21',
 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(F)cc21',
 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(I)cc21',
 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2cccc(Cl)c21',
 'O=C1C(=O)N(C/C=C/c2cc3ccccc3s2)c2ccc(I)cc21',
 'O=C(Nc1ccc(Cl)cc1)c1ccc(CN2C(=O)C(=O)c3cc(I)ccc32)s1',
 'O=C1C(=O)N(Cc2ccc(C(=O)N3CCCCC3)s2)c2ccc(I)cc21',
 'CCOC(=O)/C=C/[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@@H](CC(=O)[C@@H](NC(=O)c1cc(C)on1)C(C)C)Cc1ccccc1',
 'CCOC(=O)/C=C/[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC=C(C)C)CC(=O)[C@@H](NC(=O)c1cc(C)on1)C(C)C',
 'CCCCN1C(=O)C(=O)c2cc(I)ccc21',
 'NC(=O)c1ccc2c(c1)C(=O)C(=O)N2Cc1ccc2ccccc2c1',
 'NC(=O)c1ccc2c(c1)C(=O)C(=O)N2Cc1ccccc1',
 'CCCCN1C(=O)C(=O)c2cc(C(N)=O)ccc21',
 'CCCN1C(=O)C(=O)c2cc(C(N)=O)ccc21',
 'CN1C(=O)C(=O)c2cc(C(N)=O)ccc21',
 'O=C1C(=O)N(Cc2ccc3ccccc3c2)c2ccc(I)cc21',
 'O=C1C(=O)N(Cc2ccccc2)c2ccc(I)cc21',
 'O=C(CSc1nccc(-c2csc(-c3ccccc3)n2)n1)Nc1cc(Cl)cc(Cl)c1',
 'O=C(CSc1nccc(-c2csc(-c3ccccc3)n2)n1)Nc1cc(Cl)cc(Cl)c1',
 'COc1cccc(-c2nc(SCC(=O)Nc3ccc([N+](=O)[O-])cc3)nc(O)c2C#N)c1',
 'COc1cccc(-c2nc(SCC(=O)Nc3ccc([N+](=O)[O-])cc3)nc(O)c2C#N)c1',
 'CCOC(=O)c1cnc(SCC(=O)Nc2ccc([N+](=O)[O-])cc2)nc1N',
 'CCOC(=O)c1cnc(SCC(=O)Nc2ccc([N+](=O)[O-])cc2)nc1N',
 'COC(OC)c1cc(O)nc(SCC(=O)Nc2ccc(C(F)(F)F)cc2)n1',
 'COC(OC)c1cc(O)nc(SCC(=O)Nc2ccc(C(F)(F)F)cc2)n1',
 'Cc1cc(O)nc(SCC(=O)Nc2cc(Cl)ccc2Oc2ccccc2)n1',
 'Cc1cc(O)nc(SCC(=O)Nc2cc(Cl)ccc2Oc2ccccc2)n1',
 'CCC(Sc1nc(O)c(C#N)c(-c2cccc(OC)c2)n1)C(=O)Nc1ccc(C(C)=O)cc1',
 'CCC(Sc1nc(O)c(C#N)c(-c2cccc(OC)c2)n1)C(=O)Nc1ccc(C(C)=O)cc1',
 'COc1ccc(NC(=O)CSc2nc(O)cc(-c3ccccc3)n2)cc1OC',
 'COc1ccc(NC(=O)CSc2nc(O)cc(-c3ccccc3)n2)cc1OC',
 'CC(C)c1ccc(NC(=O)CSc2nccc(-c3cccs3)n2)cc1',
 'CC(C)c1ccc(NC(=O)CSc2nccc(-c3cccs3)n2)cc1',
 'O=C(CSc1nccc(-c2cc(-c3ccccc3Cl)no2)n1)Nc1ccc(Cl)cc1',
 'O=C(CSc1nccc(-c2cc(-c3ccccc3Cl)no2)n1)Nc1ccc(Cl)cc1',
 'O=C(CSc1nccc(-c2cc(-c3ccc(Cl)cc3Cl)no2)n1)Nc1ccc(C(F)(F)F)cc1',
 'O=C(CSc1nccc(-c2cc(-c3ccc(Cl)cc3Cl)no2)n1)Nc1ccc(C(F)(F)F)cc1',
 'CSc1sc(-c2nc(C)cs2)c(C)c1-c1ccnc(SCC(=O)Nc2ccccc2Cl)n1',
 'CSc1sc(-c2nc(C)cs2)c(C)c1-c1ccnc(SCC(=O)Nc2ccccc2Cl)n1',
 'Cc1nc(SCC(=O)Nc2ccc([N+](=O)[O-])cc2)nc(O)c1C',
 'Cc1nc(SCC(=O)Nc2ccc([N+](=O)[O-])cc2)nc(O)c1C',
 'Cc1cc(C(F)(F)F)nc(SCC(=O)Nc2ccc(Cl)cc2F)n1',
 'Cc1cc(C(F)(F)F)nc(SCC(=O)Nc2ccc(Cl)cc2F)n1',
 'COc1ccc(-c2ccnc(SCC(=O)Nc3ccc(C(C)C)cc3)n2)cc1',
 'COc1ccc(-c2ccnc(SCC(=O)Nc3ccc(C(C)C)cc3)n2)cc1',
 'CC(C)(C)c1ccc(NC(=O)CSc2nc(O)c(C#N)c(C3CCCCC3)n2)cc1',
 'CC(C)(C)c1ccc(NC(=O)CSc2nc(O)c(C#N)c(C3CCCCC3)n2)cc1',
 'CC(Sc1nc(O)c(C#N)c(-c2ccccc2)n1)C(=O)Nc1ccc(Cl)cc1',
 'CC(Sc1nc(O)c(C#N)c(-c2ccccc2)n1)C(=O)Nc1ccc(Cl)cc1',
 'CCOc1ccc(N2C(=O)CC(Sc3nc(C)cc(C)n3)C2=O)cc1',
 'CCOc1ccc(N2C(=O)CC(Sc3nc(C)cc(C)n3)C2=O)cc1',
 'N#Cc1c(O)nc(SCC(=O)Nc2cccc(C(F)(F)F)c2)nc1-c1ccccc1',
 'N#Cc1c(O)nc(SCC(=O)Nc2cccc(C(F)(F)F)c2)nc1-c1ccccc1',
 'CCCCc1ccc(NC(=O)CSc2nc(O)c(C#N)c(C3CCCCC3)n2)c(C)c1',
 'CCCCc1ccc(NC(=O)CSc2nc(O)c(C#N)c(C3CCCCC3)n2)c(C)c1',
 'CC(C)c1ccc(NC(=O)CSc2nccc(-c3csc(COc4ccccc4Cl)n3)n2)cc1',
 'CC(C)c1ccc(NC(=O)CSc2nccc(-c3csc(COc4ccccc4Cl)n3)n2)cc1',
 'Cc1cc(O)nc(SCC(=O)Nc2ccc(Oc3ccc(Cl)cc3)cc2)n1',
 'Cc1cc(O)nc(SCC(=O)Nc2ccc(Oc3ccc(Cl)cc3)cc2)n1',
 'COc1cccc(-c2nc(SCC(=O)Nc3ccc(C(C)=O)cc3)nc(O)c2C#N)c1',
 'COc1cccc(-c2nc(SCC(=O)Nc3ccc(C(C)=O)cc3)nc(O)c2C#N)c1',
 'COc1cccc(-c2nc(SCC(=O)Nc3ccc(S(N)(=O)=O)cc3)nc(O)c2C#N)c1',
 'COc1cccc(-c2nc(SCC(=O)Nc3ccc(S(N)(=O)=O)cc3)nc(O)c2C#N)c1',
 'CCCc1cc(O)nc(SCC(=O)Nc2ccc(Cl)cc2)n1',
 'CCCc1cc(O)nc(SCC(=O)Nc2ccc(Cl)cc2)n1',
 'O=C(CSc1nccc(-c2cc(-c3ccccc3)no2)n1)Nc1ccc(Cl)cc1',
 'O=C(CSc1nccc(-c2cc(-c3ccccc3)no2)n1)Nc1ccc(Cl)cc1',
 'Cc1nc(-c2nc(-c3ccnc(SCC(=O)Nc4ccc(Cl)cc4)n3)cs2)cs1',
 'Cc1nc(-c2nc(-c3ccnc(SCC(=O)Nc4ccc(Cl)cc4)n3)cs2)cs1',
 'CSc1sc(-c2nc(C)cs2)c(C)c1-c1ccnc(SCC(=O)Nc2ccc(Cl)cc2)n1',
 'CSc1sc(-c2nc(C)cs2)c(C)c1-c1ccnc(SCC(=O)Nc2ccc(Cl)cc2)n1',
 'Cn1nc(-c2ccc(-c3ccnc(SCC(=O)Nc4ccc(Cl)cc4)n3)s2)cc1C(F)(F)F',
 'Cn1nc(-c2ccc(-c3ccnc(SCC(=O)Nc4ccc(Cl)cc4)n3)s2)cc1C(F)(F)F',
 'O=C(Oc1ccc(S(=O)(=O)c2ccc(OC(=O)C(Cl)=C(Cl)Cl)cc2)cc1)C(Cl)=C(Cl)Cl',
 'Nc1ncc(S(=O)(=O)c2ccc(Cl)cc2)c(N)n1',
 'O=[N+]([O-])c1cc(C(F)(F)F)ccc1S(=O)(=O)c1ccc(Cl)cc1',
 'Cc1nc(S(=O)(=O)c2ccccc2)c(C#N)c(C)c1[N+](=O)[O-]',
 'Cc1ccc(S(=O)(=O)c2nc(C)c([N+](=O)[O-])c(C)c2C#N)cc1',
 'O=[N+]([O-])c1ccc(S(=O)(=O)c2ccc(Cl)cc2)[n+]([O-])c1',
 'CCOC(=O)/C(C#N)=C/Nc1ccc(S(=O)(=O)c2ccc(/N=C/C(C#N)=C(\\O)OCC)cc2)cc1',
 'O=C(O)c1ccc(S(=O)(=O)c2cc(Br)c(O)c(Br)c2)cc1',
 'CC(=O)c1ccccc1S(=O)(=O)c1ccccc1C(=O)O',
 'O=[N+]([O-])c1ccc(S(=O)(=O)c2ccc([N+](=O)[O-])cc2)cc1',
 'CCOC(=O)C(=CNc1ccc(S(=O)(=O)c2ccc(/N=C/C(C(=O)OCC)=C(\\O)OCC)cc2)cc1)C(=O)OCC',
 'O=C(Sc1nnc(C(F)(F)F)[nH]1)c1ccc(C#Cc2ccccc2)o1',
 'Cc1noc(NC(=O)c2ccc(-c3cc(C(F)(F)F)nn3C)s2)c1[N+](=O)[O-]',
 'Cc1oc(C(C)(C)C)cc1-c1cc(NS(=O)(=O)c2cccs2)[nH]n1',
 'CSc1[nH]nc(NC(=O)c2cccs2)c1S(=O)(=O)c1ccccc1',
 'CC1(C)CC(=O)c2c(NCc3ccco3)sc(C#N)c2C1',
 'CSc1nn(-c2c([N+](=O)[O-])c(C)nn2C)c(-c2cccs2)c1C#N',
 'O=S(=O)(Cc1[nH]c(-c2ccc(Cl)s2)c[s+]1)c1cccs1.[Br-]',
 'Cc1nn(C)c(NCc2ccc(-c3cccs3)s2)c1[N+](=O)[O-]',
 'O=C(Cc1nccs1)c1nccs1',
 'Cc1cc(S(=O)(=O)c2c([N+](=O)[O-])cc(C(F)(F)F)cc2[N+](=O)[O-])c(Cl)cc1Cl',
 'O=C(Oc1cncc(Cl)c1)c1ccco1',
 'O=C(Oc1cncc(Cl)c1)c1ccc(-c2ccc(Cl)cc2)o1',
 'COc1cccc(C(=O)Oc2cncc(Cl)c2)c1',
 'O=C(Oc1cncc(Cl)c1)c1cscn1',
 'O=C(Oc1cncc(Cl)c1)c1cc2ccccc2s1',
 'O=C(Oc1cncc(Cl)c1)c1cc2ccccc2[nH]1',
 'O=C(Oc1cncc(Br)c1)c1ccco1',
 'O=C(Oc1cncc(Cl)c1)c1cc2ccccc2o1',
 'C=C(C)[C@@H]1CC[C@]2(C(=O)O)CC[C@]3(C)[C@H](CC[C@@H]4[C@@]5(C)CC[C@H](O)C(C)(C)[C@@H]5CC[C@]43C)[C@@H]12',
 'O=C(Nc1ccc([N+](=O)[O-])cc1Cl)c1cc(Cl)ccc1O',
 'COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)c(OC)c2)ccc1O',
 'O=C1OC[C@H](Cc2ccc3c(c2)OCO3)/C1=C\\c1ccc2c(c1)OCO2',
 'O=C1OC[C@H](Cc2ccc3c(c2)OCO3)[C@H]1Cc1ccc2c(c1)OCO2',
 'C=C(C)[C@@H]1CC[C@]2(C(=O)O)CC[C@]3(C)[C@H](CC[C@@H]4[C@@]5(C)CCC(=O)C(C)(C)[C@@H]5CC[C@]43C)[C@@H]12',
 'CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F',
 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F',
 'CCCCCCCCC(=O)N[C@@H](CC(C)C)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F',
 'CCCCCCCCCC(=O)N[C@@H](CC(C)C)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F',
 'C[C@H](NC(=O)[C@@H](N)CCC(=O)O)C(=O)NCC(=O)C(F)(F)F',
 'C[C@H](NC(=O)[C@H](CCC(=O)OC(C)(C)C)NC(=O)OC(C)(C)C)C(=O)NCC(=O)C(F)(F)F',
 'CC(C)C[C@H](NC(=O)OC(C)(C)C)C(=O)NC(C)C(=O)C(F)(F)F',
 'O=C(N[C@@H](Cc1ccccc1)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F)OCc1ccccc1',
 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F',
 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F',
 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F',
 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F',
 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F',
 'O=C(CSc1nc(C2CCCCC2)nc2ccccc12)NCc1ccco1',
 'Cc1cc2cc(CN(CCc3ccccc3C)C(=O)NCc3ccccc3)c(=O)[nH]c2cc1C',
 'O=C(Oc1cncc(Cl)c1)c1cccs1',
 'O=C(Oc1cncc(Br)c1)c1ccco1',
 'N#Cc1c(-c2ccccc2)nc(SCc2ccccc2)[nH]c1=O',
 'N#Cc1c(-c2ccccc2)nc(SCCc2ccccc2)[nH]c1=O',
 'N#Cc1c(-c2ccccc2)nc(SCc2ccc([N+](=O)[O-])cc2)[nH]c1=O',
 'COc1ccc(-c2nc(SCc3ccccc3)[nH]c(=O)c2C#N)cc1',
 'COc1ccc(-c2nc(SCCc3ccccc3)[nH]c(=O)c2C#N)cc1',
 'COc1ccc(-c2nc(SCc3ccc([N+](=O)[O-])cc3)[nH]c(=O)c2C#N)cc1',
 'Cc1ccc(-c2nc(SCc3ccccc3)[nH]c(=O)c2C#N)cc1',
 'Cc1ccc(-c2nc(SCCc3ccccc3)[nH]c(=O)c2C#N)cc1',
 'Cc1ccc(-c2nc(SCc3ccc([N+](=O)[O-])cc3)[nH]c(=O)c2C#N)cc1',
 'N#Cc1c(-c2cccc([N+](=O)[O-])c2)nc(SCCc2ccccc2)[nH]c1=O',
 'N#Cc1c(-c2cccc([N+](=O)[O-])c2)nc(SCc2ccc([N+](=O)[O-])cc2)[nH]c1=O',
 'N#Cc1c(-c2ccc(Cl)cc2)nc(SCCc2ccccc2)[nH]c1=O',
 'N#Cc1c(-c2ccc(Cl)cc2)nc(SCc2ccc([N+](=O)[O-])cc2)[nH]c1=O',
 'N#Cc1c(-c2cccc(Cl)c2)nc(SCc2ccccc2)[nH]c1=O',
 'COc1ccccc1/N=C/c1nc(-c2ccccc2)oc1OC(C)=O',
 'COc1cc(C[S+]([O-])c2nc3cccnc3s2)oc(=O)c1',
 'Clc1ccc(C2C(n3ccnc3)C(c3ccc(Br)cc3)=NN2c2ccc(Cl)c(Cl)c2)cc1',
 'COc1c(Sc2nnnn2-c2ccc(OCc3ccccc3)cc2)c(=O)[nH]c2ccccc12',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)CO',
 'COC(=O)[C@@]1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(C)coc2-1',
 'C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c(C)cccc12',
 'Cc1cccc2c3c(ccc12)C1=C(C(=O)C3=O)[C@@H](C)CO1',
 'CC(C)C1=Cc2ccc3c(c2C(=O)C1=O)CCCC3(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)CO',
 'COC(=O)[C@@]1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(C)coc2-1',
 'C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c(C)cccc12',
 'Cc1cccc2c3c(ccc12)C1=C(C(=O)C3=O)[C@@H](C)CO1',
 'CC(C)C1=Cc2ccc3c(c2C(=O)C1=O)CCCC3(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)CO',
 'C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c(C)cccc12',
 'Cc1cccc2c3c(ccc12)C1=C(C(=O)C3=O)[C@@H](C)CO1',
 'CC(C)C1=Cc2ccc3c(c2C(=O)C1=O)CCCC3(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)CO',
 'COC(=O)[C@@]1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(C)coc2-1',
 'C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C',
 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c(C)cccc12',
 'Cc1cccc2c3c(ccc12)C1=C(C(=O)C3=O)[C@@H](C)CO1',
 'CC(C)C1=Cc2ccc3c(c2C(=O)C1=O)CCCC3(C)C',
 'CN(C)CCCSc1ccccc1NC(=O)/C=C/c1ccccc1',
 'CC(C)(C)NC(=O)[C@@H](c1cccnc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1',
 'CC(C)(C)NC(=O)C(c1cc[nH]n1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1',
 'CC(C)(C)NC(=O)C(c1ccccn1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1',
 'CC(C)(C)NC(=O)C(c1ccncc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1',
 'Cc1ccc(C(C(=O)NC(C)(C)C)N(C(=O)c2ccco2)c2ccc(C(C)(C)C)cc2)cn1',
 'CC(C)(C)NC(=O)C(c1cnccn1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1',
 'CC(C)(C)NC(=O)C(c1ccnnc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1',
 'Cn1cnc(C(=O)N(c2ccc(C(C)(C)C)cc2)C(C(=O)NC(C)(C)C)c2cccnc2)c1',
 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1ccc(Cl)o1)c1ccc(C(C)(C)C)cc1',
 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1ncco1)c1ccc(C(C)(C)C)cc1',
 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)C1=NC=NC1)c1ccc(C(C)(C)C)cc1',
 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1cccs1)c1ccc(C(C)(C)C)cc1',
 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1cnco1)c1ccc(C(C)(C)C)cc1',
 'CC(C)c1ccc(N(C(=O)c2ccco2)C(C(=O)NC(C)(C)C)c2cccnc2)cc1',
 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1',
 'CCC(C)c1ccc(N(C(=O)c2ccco2)C(C(=O)NC2CCCC2)c2cccnc2)cc1',
 'C=C(Cc1cccc(C)c1)C1=CC=C(c2ccc(C)cc2)C1',
 'O=C(Oc1cncc(Br)c1)c1cccs1',
 'CCN(CC)c1ccc(C(=O)On2nnc3ccccc32)cc1',
 'CC(C)C[C@@H]1NC(=O)[C@@H](NC(=O)OCc2ccccc2)Cc2cn(nn2)CCCNC(=O)CC[C@@H](C=O)NC1=O',
 'COc1ccccc1NCC(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)c1nc2ccccc2s1',
 'COc1cccc(NCC(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]2CCNC2=O)C(=O)c2nc3ccccc3s2)c1',
 'CC(C)C[C@H](NC(=O)COc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)c1nc2ccccc2s1',
 'COc1ccc(CC(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]2CCNC2=O)C(=O)c2nc3ccccc3s2)cc1',
 'CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)c1nc2ccccc2s1',
 'CN(C)CCCSc1ccccc1NC(=O)/C=C/c1ccccc1',
 'CC(=O)N[C@@H](CO)C(=O)N[C@@H](C)C(=O)N[C@H](C(=O)N[C@@H](CC1CCCCC1)C(=O)N[C@H](C=O)Cc1c[nH]cn1)C(C)C',
 'COC(=O)/C=C/[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](NC(=O)OCc1ccccc1)C(C)C',
 'CC(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CCC(=O)N(C)C)C(=O)Cn1[nH]c(=O)c2c([N+](=O)[O-])cccc2c1=O)[C@H](C)OCc1ccccc1)C(C)C',
 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F',
 'CCC(C)(C)NC(=O)[C@@H](c1ccn(C)c1)N(C(=O)Cn1nnc2ccccc21)c1ccc(NC(C)=O)cc1',
 'COc1ncc(-c2ccc(N(Cc3ccsc3)C(=O)Cn3nnc4ccccc43)cc2)cn1',
 'O=C(Cn1nnc2ccccc21)N(Cc1ccsc1)c1ccc(-c2ccncc2)cc1',
 'COc1ncccc1-c1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1',
 'O=C(Cn1nnc2ccccc21)N(Cc1ccsc1)c1ccc(-c2cccnc2)cc1',
 'O=C(Cn1nnc2ccccc21)N(Cc1ccsc1)c1ccc(-c2ccccc2)cc1',
 'O=C(Cn1nnc2ccccc21)N(Cc1ccsc1)c1ccc(NCc2ccccc2)cc1',
 'CNc1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1',
 'CC(C)COC(=O)Nc1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1',
 'O=C(Nc1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1)C1CCCCC1',
 'O=C(Nc1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1)C1CCC1',
 'COCCC(=O)Nc1ccc(N(C(=O)Cn2nnc3ccccc32)C(C)c2ccsc2)cc1',
 'CC(C)(C)C(=O)Nc1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1',
 'CC(C)C(=O)Nc1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1',
 'CCC(=O)Nc1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1',
 'CC(C)(C)NC(=O)C(c1ccsc1)N(C(=O)Cn1nnc2ccccc21)c1ccc(NC(=O)c2ccno2)cc1',
 'CC(C)(C)NC(=O)C(c1ccsc1)N(C(=O)Cn1nnc2ccccc21)c1ccc(NC(=O)C2CCC2)cc1',
 'CC(C)(C)NC(=O)C(c1ccsc1)N(C(=O)Cn1nnc2ccccc21)c1ccc(NC(=O)C2CC2)cc1',
 'CC(C)(C)NC(=O)C(c1ccsc1)N(C(=O)Cn1nnc2ccccc21)c1ccc(NC(=O)C(C)(C)C)cc1',
 'CC(C)C(=O)Nc1ccc(N(C(=O)Cn2nnc3ccccc32)C(C(=O)NC(C)(C)C)c2ccsc2)cc1',
 'CCC(=O)Nc1ccc(N(C(=O)Cn2nnc3ccccc32)C(C(=O)NC(C)(C)C)c2ccsc2)cc1',
 'CC(C)(C)NC(=O)C(c1ccsc1)N(C(=O)Cn1nnc2ccccc21)c1ccc(NS(C)(=O)=O)cc1',
 'CC(=O)Nc1ccc(N(C(=O)Cn2nnc3ccccc32)C(C(=O)NC(C)(C)C)c2ccsc2)cc1',
 'CC(C)(C)NC(=O)C(c1ccsc1)N(C(=O)Cn1nnc2ccccc21)c1ccc(N)cc1',
 'CC(=O)Nc1ccc(N(C(=O)Cn2cc(-c3ccccc3)nn2)C(C(=O)NC(C)(C)C)c2ccsc2)cc1',
 'C=C(Cc1cccc(C)c1)C1=CC=C(c2ccc(C)cc2)C1',
 'CN(C)CCCSc1ccccc1NC(=O)/C=C/c1ccccc1',
 'O=C(Oc1cncc(Br)c1)c1cccs1',
 'O=C(Nc1ccc(N(Cc2ccsc2)C(=O)Cn2nnc3ccccc32)cc1)C1CC1',
 'CC(=O)N[C@H](C(=O)NCC(=O)NC1[C@H]2CCCC[C@@H]2CN(C(=O)c2ccc(Br)cc2)[C@@H]1CN[C@H](C=O)Cc1c[nH]cn1)[C@@H](C)O',
 'CCSC(SCC)[C@H](Cc1c[nH]cn1)NC[C@@H]1C(NC(=O)CNC(=O)[C@@H](NC(C)=O)[C@@H](C)O)[C@H]2CCCC[C@@H]2CN1C(=O)c1ccc(Br)cc1',
 'CON(C)C(=O)[C@H](Cc1c[nH]cn1)NC[C@@H]1C(NC(=O)CNC(=O)[C@@H](NC(C)=O)[C@@H](C)O)[C@H]2CCCC[C@@H]2CN1C(=O)c1ccc(Br)cc1',
 'CCOC(=O)/C=C/[C@H](Cc1c[nH]cn1)NC[C@@H]1C(NC(=O)CNC(=O)[C@@H](NC(C)=O)[C@@H](C)O)[C@H]2CCCC[C@@H]2CN1C(=O)c1ccc(Br)cc1',
 'CN(C)CCCSc1ccccc1NC(=O)/C=C/c1ccccc1',
 'Cc1cccc2nc(CSC(=S)NCc3cccnc3)cn12',
 'Cc1cccc2nc(CSC(=S)NCc3cccnc3)cn12',
 'S=C([S-])NCc1cccnc1.[K+]',
 'CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1CCNC1=O)C(O)S(=O)(=O)O',
 'S=C([S-])NCc1cccnc1.[K+]',
 'CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](CC1CCNC1=O)C(O)S(=O)(=O)O',
 'O=C[C@H](CC1CCNC1=O)NC(=O)[C@H](CC1CCCCC1)NC(=O)c1cc2ccccc2[nH]1',
 'CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@H](C=O)C[C@@H]1CCNC1=O',
 'CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(O)S(=O)(=O)[O-].[Na+]',
 'CCCCC1CCC(COC(=O)N[C@@H](CC(C)C)C(=O)N[C@H](C=O)C[C@@H]2CCNC2=O)CC1',
 'CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CCNC3=O)N(C(=O)COc3ccc(OC(F)(F)F)cc3)C[C@@H]21',
 'CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CCNC3=O)N(C(=O)COc3ccccc3)C[C@@H]21',
 'CC(C)(C)NC(=O)N[C@H](C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)NC(CC1CCC1)C(=O)C(N)=O)C2(C)C)C(C)(C)C',
 'CC(C)(C)NC(=O)[C@@H](c1cccnc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1',
 'C=CC(=O)N[C@H](CC(=C)C)C(=O)N1C[C@@H](C(=O)N[C@H](Cc2ccccc2)C(=O)NC)[C@H](c2cccc(C(F)(F)F)c2)C1',
 'CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CCNC3=O)N(C(=O)c3cc4ccccc4[nH]3)C[C@@H]21',
 'CC(C)c1ccc(F)c2[nH]c(C(=O)N3C[C@H]4[C@@H]([C@H]3C(=O)N[C@H](C=O)C[C@@H]3CCNC3=O)C4(C)C)cc12',
 'CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CCNC3=O)N(C(=O)C3(c4cccc(Cl)c4)CC3)C[C@@H]21',
 'CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CCNC3=O)N(C(=O)C3(c4ccccc4)CCCC3)C[C@@H]21',
 'CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@@H]([C@H]1C(=O)N[C@H](C#N)C[C@@H]1CCNC1=O)C2(C)C',
 'O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC1CCCCC1)NC(=O)c1cc2ccccc2[nH]1',
 'O=C[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](Cc1cccc(F)c1)NC(=O)c1cc2ccccc2[nH]1',
 'CC[C@H](C)[C@H]1C(=O)N2CCC[C@H]2C(=O)O[C@H](C(C)(C)C)C[C@@H](C)C[C@H](O)[C@H](C)C2=N[C@@H](CCC(=O)N[C@@H](Cc3ccc(OC)cc3)C(=O)N(C)[C@@H](C)C(=O)N1C)CS2']

### **Iterate *standard_value* to a list**

In [41]:
standard_value = []
for i in df2.standard_value:
  standard_value.append(i)

In [42]:
standard_value

['7200.0',
 '9400.0',
 '13500.0',
 '13110.0',
 '2000.0',
 '980.0',
 '4820.0',
 '950.0',
 '11200.0',
 '23500.0',
 '12570.0',
 '17500.0',
 '45000.0',
 '70000.0',
 '66000.0',
 '370.0',
 '12500.0',
 '19000.0',
 '25000.0',
 '71000.0',
 '1100.0',
 '50000.0',
 '3019.95',
 '3000.0',
 '301995.17',
 '300000.0',
 '251188.64',
 '250000.0',
 '204173.79',
 '200000.0',
 '100000.0',
 '100000.0',
 '60255.96',
 '60000.0',
 '45708.82',
 '45000.0',
 '40738.03',
 '40000.0',
 '15135.61',
 '15000.0',
 '15135.61',
 '15000.0',
 '12022.64',
 '12000.0',
 '1000000.0',
 '1000000.0',
 '501187.23',
 '500000.0',
 '407380.28',
 '400000.0',
 '354813.39',
 '350000.0',
 '301995.17',
 '300000.0',
 '301995.17',
 '300000.0',
 '204173.79',
 '200000.0',
 '204173.79',
 '200000.0',
 '204173.79',
 '200000.0',
 '204173.79',
 '200000.0',
 '60255.96',
 '60000.0',
 '40738.03',
 '40000.0',
 '30199.52',
 '30000.0',
 '15135.61',
 '15000.0',
 '14125.38',
 '14000.0',
 '11220.18',
 '11000.0',
 '10000.0',
 '10000.0',
 '900.0',
 '6000.0',
 '12000.0',
 '13000.0',
 '13000.0',
 '15000.0',
 '16000.0',
 '16000.0',
 '16000.0',
 '25000.0',
 '32000.0',
 '3000.0',
 '5000.0',
 '10000.0',
 '15000.0',
 '16000.0',
 '18000.0',
 '18000.0',
 '20000.0',
 '40000.0',
 '300.0',
 '60.0',
 '63.0',
 '340.0',
 '270.0',
 '95.0',
 '65.0',
 '50.0',
 '170.0',
 '10000.0',
 '40000.0',
 '40000.0',
 '25000.0',
 '100000.0',
 '100000.0',
 '15000.0',
 '10000.0',
 '50000.0',
 '50000.0',
 '50000.0',
 '40000.0',
 '40000.0',
 '20000.0',
 '10000.0',
 '7000.0',
 '4000.0',
 '2000.0',
 '800.0',
 '18200.0',
 '17200.0',
 '500.0',
 '50.0',
 '50000.0',
 '50000.0',
 '35200.0',
 '50000.0',
 '20300.0',
 '26300.0',
 '50000.0',
 '50000.0',
 '50000.0',
 '50000.0',
 '10600.0',
 '16900.0',
 '6100.0',
 '50000.0',
 '3300.0',
 '7200.0',
 '2500.0',
 '2000.0',
 '89100.0',
 '24800.0',
 '21100.0',
 '226700.0',
 '38700.0',
 '14400.0',
 '21100.0',
 '1600.0',
 '10700.0',
 '9200.0',
 '800.0',
 '8800.0',
 '4900.0',
 '30000.0',
 '52000.0',
 '87600.0',
 '700.0',
 '1200.0',
 '60200.0',
 '17100.0',
 '18000.0',
 '10600.0',
 '10100.0',
 '11500.0',
 '10700.0',
 '78900.0',
 '5000.0',
 '1500.0',
 '300.0',
 '300.0',
 '45000.0',
 '300.0',
 '5500.0',
 '10000.0',
 '75000.0',
 '5200.0',
 '47000.0',
 '6000.0',
 '50000.0',
 '39000.0',
 '28100.0',
 '4800.0',
 '2200.0',
 '13000.0',
 '500.0',
 '11100.0',
 '15500.0',
 '14000.0',
 '10000.0',
 '24000.0',
 '43000.0',
 '21000.0',
 '323000.0',
 '65.0',
 '9100.0',
 '600.0',
 '10000.0',
 '6200.0',
 '12500.0',
 '2000.0',
 '700.0',
 '970.0',
 '51.0',
 '1500.0',
 '2100.0',
 '10300.0',
 '22100.0',
 '8100.0',
 '3400.0',
 '13300.0',
 '3600.0',
 '2900.0',
 '26000.0',
 '3800.0',
 '9100.0',
 '22500.0',
 '4100.0',
 '6900.0',
 '25300.0',
 '7720.0',
 '20000.0',
 '11000.0',
 '13000.0',
 '5000.0',
 '500.0',
 '4100.0',
 '26000.0',
 '175000.0',
 '1000000.0',
 '2000000.0',
 '5000.0',
 '383.0',
 '380.19',
 '165.0',
 '161.0',
 '165.96',
 '162.18',
 '53.0',
 '70.0',
 '50.0',
 '900.0',
 '15.2',
 '99.0',
 '6630.0',
 '1500.0',
 '3500.0',
 '52.0',
 '30.0',
 '14.0',
 '48.0',
 '20.0',
 '53.0',
 '40.0',
 '170.0']

### **Combine the 4 lists into a dataframe**

In [44]:
data_tuples = list(zip(mol_cid, canonical_smiles, bioactivity_class, standard_value))
df3 = pd.DataFrame( data_tuples,  columns=['molecule_chembl_id', 'canonical_smiles', 'bioactivity_class', 'standard_value'])

[('CHEMBL187579', 'Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21', 'intermediate', '7200.0'), ('CHEMBL188487', 'O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21', 'intermediate', '9400.0'), ('CHEMBL185698', 'O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21', 'inactive', '13500.0'), ('CHEMBL426082', 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21', 'inactive', '13110.0'), ('CHEMBL187717', 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-]', 'intermediate', '2000.0'), ('CHEMBL365134', 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2c(Br)cccc21', 'active', '980.0'), ('CHEMBL187598', 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(F)cc21', 'intermediate', '4820.0'), ('CHEMBL190743', 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccc(I)cc21', 'active', '950.0'), ('CHEMBL365469', 'O=C1C(=O)N(Cc2cc3ccccc3s2)c2cccc(Cl)c21', 'inactive', '11200.0'), ('CHEMBL188983', 'O=C1C(=O)N(C/C=C/c2cc3ccccc3s2)c2ccc(I)cc21', 'inactive', '23500.0'), ('CHEMBL191575', 'O=C(Nc1ccc(Cl)cc1)c1ccc(CN2C(=O)C(=O)c3cc(I)ccc32)s1', 'inactive', '12570.0'), ('CHEMBL370923', 'O=C1C(=O)N(Cc2ccc(C(=O)N3CCCCC3)s2)c2ccc(I)cc21', 'inactive', '17500.0'), ('CHEMBL194398', 'CCOC(=O)/C=C/[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@@H](CC(=O)[C@@H](NC(=O)c1cc(C)on1)C(C)C)Cc1ccccc1', 'inactive', '45000.0'), ('CHEMBL196635', 'CCOC(=O)/C=C/[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC=C(C)C)CC(=O)[C@@H](NC(=O)c1cc(C)on1)C(C)C', 'inactive', '70000.0'), ('CHEMBL209287', 'CCCCN1C(=O)C(=O)c2cc(I)ccc21', 'inactive', '66000.0'), ('CHEMBL358279', 'NC(=O)c1ccc2c(c1)C(=O)C(=O)N2Cc1ccc2ccccc2c1', 'active', '370.0'), ('CHEMBL348660', 'NC(=O)c1ccc2c(c1)C(=O)C(=O)N2Cc1ccccc1', 'inactive', '12500.0'), ('CHEMBL379727', 'CCCCN1C(=O)C(=O)c2cc(C(N)=O)ccc21', 'inactive', '19000.0'), ('CHEMBL210525', 'CCCN1C(=O)C(=O)c2cc(C(N)=O)ccc21', 'inactive', '25000.0'), ('CHEMBL148483', 'CN1C(=O)C(=O)c2cc(C(N)=O)ccc21', 'inactive', '71000.0'), ('CHEMBL383725', 'O=C1C(=O)N(Cc2ccc3ccccc3c2)c2ccc(I)cc21', 'intermediate', '1100.0'), ('CHEMBL118596', 'O=C1C(=O)N(Cc2ccccc2)c2ccc(I)cc21', 'inactive', '50000.0'), ('CHEMBL208732', 'O=C(CSc1nccc(-c2csc(-c3ccccc3)n2)n1)Nc1cc(Cl)cc(Cl)c1', 'intermediate', '3019.95'), ('CHEMBL208732', 'O=C(CSc1nccc(-c2csc(-c3ccccc3)n2)n1)Nc1cc(Cl)cc(Cl)c1', 'intermediate', '3000.0'), ('CHEMBL210146', 'COc1cccc(-c2nc(SCC(=O)Nc3ccc([N+](=O)[O-])cc3)nc(O)c2C#N)c1', 'inactive', '301995.17'), ('CHEMBL210146', 'COc1cccc(-c2nc(SCC(=O)Nc3ccc([N+](=O)[O-])cc3)nc(O)c2C#N)c1', 'inactive', '300000.0'), ('CHEMBL207458', 'CCOC(=O)c1cnc(SCC(=O)Nc2ccc([N+](=O)[O-])cc2)nc1N', 'inactive', '251188.64'), ('CHEMBL207458', 'CCOC(=O)c1cnc(SCC(=O)Nc2ccc([N+](=O)[O-])cc2)nc1N', 'inactive', '250000.0'), ('CHEMBL207484', 'COC(OC)c1cc(O)nc(SCC(=O)Nc2ccc(C(F)(F)F)cc2)n1', 'inactive', '204173.79'), ('CHEMBL207484', 'COC(OC)c1cc(O)nc(SCC(=O)Nc2ccc(C(F)(F)F)cc2)n1', 'inactive', '200000.0'), ('CHEMBL207207', 'Cc1cc(O)nc(SCC(=O)Nc2cc(Cl)ccc2Oc2ccccc2)n1', 'inactive', '100000.0'), ('CHEMBL207207', 'Cc1cc(O)nc(SCC(=O)Nc2cc(Cl)ccc2Oc2ccccc2)n1', 'inactive', '100000.0'), ('CHEMBL210487', 'CCC(Sc1nc(O)c(C#N)c(-c2cccc(OC)c2)n1)C(=O)Nc1ccc(C(C)=O)cc1', 'inactive', '60255.96'), ('CHEMBL210487', 'CCC(Sc1nc(O)c(C#N)c(-c2cccc(OC)c2)n1)C(=O)Nc1ccc(C(C)=O)cc1', 'inactive', '60000.0'), ('CHEMBL380470', 'COc1ccc(NC(=O)CSc2nc(O)cc(-c3ccccc3)n2)cc1OC', 'inactive', '45708.82'), ('CHEMBL380470', 'COc1ccc(NC(=O)CSc2nc(O)cc(-c3ccccc3)n2)cc1OC', 'inactive', '45000.0'), ('CHEMBL210612', 'CC(C)c1ccc(NC(=O)CSc2nccc(-c3cccs3)n2)cc1', 'inactive', '40738.03'), ('CHEMBL210612', 'CC(C)c1ccc(NC(=O)CSc2nccc(-c3cccs3)n2)cc1', 'inactive', '40000.0'), ('CHEMBL209667', 'O=C(CSc1nccc(-c2cc(-c3ccccc3Cl)no2)n1)Nc1ccc(Cl)cc1', 'inactive', '15135.61'), ('CHEMBL209667', 'O=C(CSc1nccc(-c2cc(-c3ccccc3Cl)no2)n1)Nc1ccc(Cl)cc1', 'inactive', '15000.0'), ('CHEMBL210097', 'O=C(CSc1nccc(-c2cc(-c3ccc(Cl)cc3Cl)no2)n1)Nc1ccc(C(F)(F)F)cc1', 'inactive', '15135.61'), ('CHEMBL210097', 'O=C(CSc1nccc(-c2cc(-c3ccc(Cl)cc3Cl)no2)n1)Nc1ccc(C(F)(F)F)cc1', 'inactive', '15000.0'), ('CHEMBL378674', 'CSc1sc(-c2nc(C)cs2)c(C)c1-c1ccnc(SCC(=O)Nc2ccccc2Cl)n1', 'inactive', '12022.64'), ('CHEMBL378674', 'CSc1sc(-c2nc(C)cs2)c(C)c1-c1ccnc(SCC(=O)Nc2ccccc2Cl)n1', 'inactive', '12000.0'), ('CHEMBL210216', 'Cc1nc(SCC(=O)Nc2ccc([N+](=O)[O-])cc2)nc(O)c1C', 'inactive', '1000000.0'), ('CHEMBL210216', 'Cc1nc(SCC(=O)Nc2ccc([N+](=O)[O-])cc2)nc(O)c1C', 'inactive', '1000000.0'), ('CHEMBL210195', 'Cc1cc(C(F)(F)F)nc(SCC(=O)Nc2ccc(Cl)cc2F)n1', 'inactive', '501187.23'), ('CHEMBL210195', 'Cc1cc(C(F)(F)F)nc(SCC(=O)Nc2ccc(Cl)cc2F)n1', 'inactive', '500000.0'), ('CHEMBL210437', 'COc1ccc(-c2ccnc(SCC(=O)Nc3ccc(C(C)C)cc3)n2)cc1', 'inactive', '407380.28'), ('CHEMBL210437', 'COc1ccc(-c2ccnc(SCC(=O)Nc3ccc(C(C)C)cc3)n2)cc1', 'inactive', '400000.0'), ('CHEMBL378677', 'CC(C)(C)c1ccc(NC(=O)CSc2nc(O)c(C#N)c(C3CCCCC3)n2)cc1', 'inactive', '354813.39'), ('CHEMBL378677', 'CC(C)(C)c1ccc(NC(=O)CSc2nc(O)c(C#N)c(C3CCCCC3)n2)cc1', 'inactive', '350000.0'), ('CHEMBL210972', 'CC(Sc1nc(O)c(C#N)c(-c2ccccc2)n1)C(=O)Nc1ccc(Cl)cc1', 'inactive', '301995.17'), ('CHEMBL210972', 'CC(Sc1nc(O)c(C#N)c(-c2ccccc2)n1)C(=O)Nc1ccc(Cl)cc1', 'inactive', '300000.0'), ('CHEMBL210145', 'CCOc1ccc(N2C(=O)CC(Sc3nc(C)cc(C)n3)C2=O)cc1', 'inactive', '301995.17'), ('CHEMBL210145', 'CCOc1ccc(N2C(=O)CC(Sc3nc(C)cc(C)n3)C2=O)cc1', 'inactive', '300000.0'), ('CHEMBL377225', 'N#Cc1c(O)nc(SCC(=O)Nc2cccc(C(F)(F)F)c2)nc1-c1ccccc1', 'inactive', '204173.79'), ('CHEMBL377225', 'N#Cc1c(O)nc(SCC(=O)Nc2cccc(C(F)(F)F)c2)nc1-c1ccccc1', 'inactive', '200000.0'), ('CHEMBL210823', 'CCCCc1ccc(NC(=O)CSc2nc(O)c(C#N)c(C3CCCCC3)n2)c(C)c1', 'inactive', '204173.79'), ('CHEMBL210823', 'CCCCc1ccc(NC(=O)CSc2nc(O)c(C#N)c(C3CCCCC3)n2)c(C)c1', 'inactive', '200000.0'), ('CHEMBL207381', 'CC(C)c1ccc(NC(=O)CSc2nccc(-c3csc(COc4ccccc4Cl)n3)n2)cc1', 'inactive', '204173.79'), ('CHEMBL207381', 'CC(C)c1ccc(NC(=O)CSc2nccc(-c3csc(COc4ccccc4Cl)n3)n2)cc1', 'inactive', '200000.0'), ('CHEMBL210511', 'Cc1cc(O)nc(SCC(=O)Nc2ccc(Oc3ccc(Cl)cc3)cc2)n1', 'inactive', '204173.79'), ('CHEMBL210511', 'Cc1cc(O)nc(SCC(=O)Nc2ccc(Oc3ccc(Cl)cc3)cc2)n1', 'inactive', '200000.0'), ('CHEMBL210632', 'COc1cccc(-c2nc(SCC(=O)Nc3ccc(C(C)=O)cc3)nc(O)c2C#N)c1', 'inactive', '60255.96'), ('CHEMBL210632', 'COc1cccc(-c2nc(SCC(=O)Nc3ccc(C(C)=O)cc3)nc(O)c2C#N)c1', 'inactive', '60000.0'), ('CHEMBL210497', 'COc1cccc(-c2nc(SCC(=O)Nc3ccc(S(N)(=O)=O)cc3)nc(O)c2C#N)c1', 'inactive', '40738.03'), ('CHEMBL210497', 'COc1cccc(-c2nc(SCC(=O)Nc3ccc(S(N)(=O)=O)cc3)nc(O)c2C#N)c1', 'inactive', '40000.0'), ('CHEMBL208584', 'CCCc1cc(O)nc(SCC(=O)Nc2ccc(Cl)cc2)n1', 'inactive', '30199.52'), ('CHEMBL208584', 'CCCc1cc(O)nc(SCC(=O)Nc2ccc(Cl)cc2)n1', 'inactive', '30000.0'), ('CHEMBL208763', 'O=C(CSc1nccc(-c2cc(-c3ccccc3)no2)n1)Nc1ccc(Cl)cc1', 'inactive', '15135.61'), ('CHEMBL208763', 'O=C(CSc1nccc(-c2cc(-c3ccccc3)no2)n1)Nc1ccc(Cl)cc1', 'inactive', '15000.0'), ('CHEMBL209227', 'Cc1nc(-c2nc(-c3ccnc(SCC(=O)Nc4ccc(Cl)cc4)n3)cs2)cs1', 'inactive', '14125.38'), ('CHEMBL209227', 'Cc1nc(-c2nc(-c3ccnc(SCC(=O)Nc4ccc(Cl)cc4)n3)cs2)cs1', 'inactive', '14000.0'), ('CHEMBL210092', 'CSc1sc(-c2nc(C)cs2)c(C)c1-c1ccnc(SCC(=O)Nc2ccc(Cl)cc2)n1', 'inactive', '11220.18'), ('CHEMBL210092', 'CSc1sc(-c2nc(C)cs2)c(C)c1-c1ccnc(SCC(=O)Nc2ccc(Cl)cc2)n1', 'inactive', '11000.0'), ('CHEMBL377150', 'Cn1nc(-c2ccc(-c3ccnc(SCC(=O)Nc4ccc(Cl)cc4)n3)s2)cc1C(F)(F)F', 'inactive', '10000.0'), ('CHEMBL377150', 'Cn1nc(-c2ccc(-c3ccnc(SCC(=O)Nc4ccc(Cl)cc4)n3)s2)cc1C(F)(F)F', 'inactive', '10000.0'), ('CHEMBL212454', 'O=C(Oc1ccc(S(=O)(=O)c2ccc(OC(=O)C(Cl)=C(Cl)Cl)cc2)cc1)C(Cl)=C(Cl)Cl', 'active', '900.0'), ('CHEMBL213581', 'Nc1ncc(S(=O)(=O)c2ccc(Cl)cc2)c(N)n1', 'intermediate', '6000.0'), ('CHEMBL380403', 'O=[N+]([O-])c1cc(C(F)(F)F)ccc1S(=O)(=O)c1ccc(Cl)cc1', 'inactive', '12000.0'), ('CHEMBL212504', 'Cc1nc(S(=O)(=O)c2ccccc2)c(C#N)c(C)c1[N+](=O)[O-]', 'inactive', '13000.0'), ('CHEMBL211969', 'Cc1ccc(S(=O)(=O)c2nc(C)c([N+](=O)[O-])c(C)c2C#N)cc1', 'inactive', '13000.0'), ('CHEMBL384739', 'O=[N+]([O-])c1ccc(S(=O)(=O)c2ccc(Cl)cc2)[n+]([O-])c1', 'inactive', '15000.0'), ('CHEMBL215732', 'CCOC(=O)/C(C#N)=C/Nc1ccc(S(=O)(=O)c2ccc(/N=C/C(C#N)=C(\\O)OCC)cc2)cc1', 'inactive', '16000.0'), ('CHEMBL212240', 'O=C(O)c1ccc(S(=O)(=O)c2cc(Br)c(O)c(Br)c2)cc1', 'inactive', '16000.0'), ('CHEMBL377253', 'CC(=O)c1ccccc1S(=O)(=O)c1ccccc1C(=O)O', 'inactive', '16000.0'), ('CHEMBL215397', 'O=[N+]([O-])c1ccc(S(=O)(=O)c2ccc([N+](=O)[O-])cc2)cc1', 'inactive', '25000.0'), ('CHEMBL378342', 'CCOC(=O)C(=CNc1ccc(S(=O)(=O)c2ccc(/N=C/C(C(=O)OCC)=C(\\O)OCC)cc2)cc1)C(=O)OCC', 'inactive', '32000.0'), ('CHEMBL379642', 'O=C(Sc1nnc(C(F)(F)F)[nH]1)c1ccc(C#Cc2ccccc2)o1', 'intermediate', '3000.0'), ('CHEMBL427404', 'Cc1noc(NC(=O)c2ccc(-c3cc(C(F)(F)F)nn3C)s2)c1[N+](=O)[O-]', 'intermediate', '5000.0'), ('CHEMBL212190', 'Cc1oc(C(C)(C)C)cc1-c1cc(NS(=O)(=O)c2cccs2)[nH]n1', 'inactive', '10000.0'), ('CHEMBL378700', 'CSc1[nH]nc(NC(=O)c2cccs2)c1S(=O)(=O)c1ccccc1', 'inactive', '15000.0'), ('CHEMBL212019', 'CC1(C)CC(=O)c2c(NCc3ccco3)sc(C#N)c2C1', 'inactive', '16000.0'), ('CHEMBL212399', 'CSc1nn(-c2c([N+](=O)[O-])c(C)nn2C)c(-c2cccs2)c1C#N', 'inactive', '18000.0'), ('CHEMBL215733', 'O=S(=O)(Cc1[nH]c(-c2ccc(Cl)s2)c[s+]1)c1cccs1.[Br-]', 'inactive', '18000.0'), ('CHEMBL375130', 'Cc1nn(C)c(NCc2ccc(-c3cccs3)s2)c1[N+](=O)[O-]', 'inactive', '20000.0'), ('CHEMBL214372', 'O=C(Cc1nccs1)c1nccs1', 'inactive', '40000.0'), ('CHEMBL212218', 'Cc1cc(S(=O)(=O)c2c([N+](=O)[O-])cc(C(F)(F)F)cc2[N+](=O)[O-])c(Cl)cc1Cl', 'active', '300.0'), ('CHEMBL222840', 'O=C(Oc1cncc(Cl)c1)c1ccco1', 'active', '60.0'), ('CHEMBL222769', 'O=C(Oc1cncc(Cl)c1)c1ccc(-c2ccc(Cl)cc2)o1', 'active', '63.0'), ('CHEMBL222735', 'COc1cccc(C(=O)Oc2cncc(Cl)c2)c1', 'active', '340.0'), ('CHEMBL222628', 'O=C(Oc1cncc(Cl)c1)c1cscn1', 'active', '270.0'), ('CHEMBL222893', 'O=C(Oc1cncc(Cl)c1)c1cc2ccccc2s1', 'active', '95.0'), ('CHEMBL225515', 'O=C(Oc1cncc(Cl)c1)c1cc2ccccc2[nH]1', 'active', '65.0'), ('CHEMBL222234', 'O=C(Oc1cncc(Br)c1)c1ccco1', 'active', '50.0'), ('CHEMBL426898', 'O=C(Oc1cncc(Cl)c1)c1cc2ccccc2o1', 'active', '170.0'), ('CHEMBL269277', 'C=C(C)[C@@H]1CC[C@]2(C(=O)O)CC[C@]3(C)[C@H](CC[C@@H]4[C@@]5(C)CC[C@H](O)C(C)(C)[C@@H]5CC[C@]43C)[C@@H]12', 'inactive', '10000.0'), ('CHEMBL1448', 'O=C(Nc1ccc([N+](=O)[O-])cc1Cl)c1cc(Cl)ccc1O', 'inactive', '40000.0'), ('CHEMBL140', 'COc1cc(/C=C/C(=O)CC(=O)/C=C/c2ccc(O)c(OC)c2)ccc1O', 'inactive', '40000.0'), ('CHEMBL395263', 'O=C1OC[C@H](Cc2ccc3c(c2)OCO3)/C1=C\\c1ccc2c(c1)OCO2', 'inactive', '25000.0'), ('CHEMBL242011', 'O=C1OC[C@H](Cc2ccc3c(c2)OCO3)[C@H]1Cc1ccc2c(c1)OCO2', 'inactive', '100000.0'), ('CHEMBL431525', 'C=C(C)[C@@H]1CC[C@]2(C(=O)O)CC[C@]3(C)[C@H](CC[C@@H]4[C@@]5(C)CCC(=O)C(C)(C)[C@@H]5CC[C@]43C)[C@@H]12', 'inactive', '100000.0'), ('CHEMBL258787', 'CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F', 'inactive', '15000.0'), ('CHEMBL2372143', 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F', 'inactive', '10000.0'), ('CHEMBL259622', 'CCCCCCCCC(=O)N[C@@H](CC(C)C)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F', 'inactive', '50000.0'), ('CHEMBL261189', 'CCCCCCCCCC(=O)N[C@@H](CC(C)C)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F', 'inactive', '50000.0'), ('CHEMBL265704', 'C[C@H](NC(=O)[C@@H](N)CCC(=O)O)C(=O)NCC(=O)C(F)(F)F', 'inactive', '50000.0'), ('CHEMBL261402', 'C[C@H](NC(=O)[C@H](CCC(=O)OC(C)(C)C)NC(=O)OC(C)(C)C)C(=O)NCC(=O)C(F)(F)F', 'inactive', '40000.0'), ('CHEMBL258581', 'CC(C)C[C@H](NC(=O)OC(C)(C)C)C(=O)NC(C)C(=O)C(F)(F)F', 'inactive', '40000.0'), ('CHEMBL409422', 'O=C(N[C@@H](Cc1ccccc1)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F)OCc1ccccc1', 'inactive', '20000.0'), ('CHEMBL2372143', 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F', 'inactive', '10000.0'), ('CHEMBL2372143', 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F', 'intermediate', '7000.0'), ('CHEMBL2372143', 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F', 'intermediate', '4000.0'), ('CHEMBL2372143', 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F', 'intermediate', '2000.0'), ('CHEMBL2372143', 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)N[C@@H](Cc1ccccc1)C(=O)C(F)(F)F', 'active', '800.0'), ('CHEMBL523052', 'O=C(CSc1nc(C2CCCCC2)nc2ccccc12)NCc1ccco1', 'inactive', '18200.0'), ('CHEMBL495231', 'Cc1cc2cc(CN(CCc3ccccc3C)C(=O)NCc3ccccc3)c(=O)[nH]c2cc1C', 'inactive', '17200.0'), ('CHEMBL468553', 'O=C(Oc1cncc(Cl)c1)c1cccs1', 'active', '500.0'), ('CHEMBL222234', 'O=C(Oc1cncc(Br)c1)c1ccco1', 'active', '50.0'), ('CHEMBL1082811', 'N#Cc1c(-c2ccccc2)nc(SCc2ccccc2)[nH]c1=O', 'inactive', '50000.0'), ('CHEMBL1082812', 'N#Cc1c(-c2ccccc2)nc(SCCc2ccccc2)[nH]c1=O', 'inactive', '50000.0'), ('CHEMBL1083123', 'N#Cc1c(-c2ccccc2)nc(SCc2ccc([N+](=O)[O-])cc2)[nH]c1=O', 'inactive', '35200.0'), ('CHEMBL1083124', 'COc1ccc(-c2nc(SCc3ccccc3)[nH]c(=O)c2C#N)cc1', 'inactive', '50000.0'), ('CHEMBL1082714', 'COc1ccc(-c2nc(SCCc3ccccc3)[nH]c(=O)c2C#N)cc1', 'inactive', '20300.0'), ('CHEMBL1082715', 'COc1ccc(-c2nc(SCc3ccc([N+](=O)[O-])cc3)[nH]c(=O)c2C#N)cc1', 'inactive', '26300.0'), ('CHEMBL327313', 'Cc1ccc(-c2nc(SCc3ccccc3)[nH]c(=O)c2C#N)cc1', 'inactive', '50000.0'), ('CHEMBL1083958', 'Cc1ccc(-c2nc(SCCc3ccccc3)[nH]c(=O)c2C#N)cc1', 'inactive', '50000.0'), ('CHEMBL1083959', 'Cc1ccc(-c2nc(SCc3ccc([N+](=O)[O-])cc3)[nH]c(=O)c2C#N)cc1', 'inactive', '50000.0'), ('CHEMBL1083286', 'N#Cc1c(-c2cccc([N+](=O)[O-])c2)nc(SCCc2ccccc2)[nH]c1=O', 'inactive', '50000.0'), ('CHEMBL1082332', 'N#Cc1c(-c2cccc([N+](=O)[O-])c2)nc(SCc2ccc([N+](=O)[O-])cc2)[nH]c1=O', 'inactive', '10600.0'), ('CHEMBL1086234', 'N#Cc1c(-c2ccc(Cl)cc2)nc(SCCc2ccccc2)[nH]c1=O', 'inactive', '16900.0'), ('CHEMBL1082333', 'N#Cc1c(-c2ccc(Cl)cc2)nc(SCc2ccc([N+](=O)[O-])cc2)[nH]c1=O', 'intermediate', '6100.0'), ('CHEMBL1082334', 'N#Cc1c(-c2cccc(Cl)c2)nc(SCc2ccccc2)[nH]c1=O', 'inactive', '50000.0'), ('CHEMBL1084478', 'COc1ccccc1/N=C/c1nc(-c2ccccc2)oc1OC(C)=O', 'intermediate', '3300.0'), ('CHEMBL1084479', 'COc1cc(C[S+]([O-])c2nc3cccnc3s2)oc(=O)c1', 'intermediate', '7200.0'), ('CHEMBL1084480', 'Clc1ccc(C2C(n3ccnc3)C(c3ccc(Br)cc3)=NN2c2ccc(Cl)c(Cl)c2)cc1', 'intermediate', '2500.0'), ('CHEMBL1084481', 'COc1c(Sc2nnnn2-c2ccc(OCc3ccccc3)cc2)c(=O)[nH]c2ccccc12', 'intermediate', '2000.0'), ('CHEMBL187266', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C', 'inactive', '89100.0'), ('CHEMBL215254', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)CO', 'inactive', '24800.0'), ('CHEMBL2146517', 'COC(=O)[C@@]1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(C)coc2-1', 'inactive', '21100.0'), ('CHEMBL187460', 'C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C', 'inactive', '226700.0'), ('CHEMBL363535', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c(C)cccc12', 'inactive', '38700.0'), ('CHEMBL227075', 'Cc1cccc2c3c(ccc12)C1=C(C(=O)C3=O)[C@@H](C)CO1', 'inactive', '14400.0'), ('CHEMBL45830', 'CC(C)C1=Cc2ccc3c(c2C(=O)C1=O)CCCC3(C)C', 'inactive', '21100.0'), ('CHEMBL187266', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C', 'intermediate', '1600.0'), ('CHEMBL215254', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)CO', 'inactive', '10700.0'), ('CHEMBL2146517', 'COC(=O)[C@@]1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(C)coc2-1', 'intermediate', '9200.0'), ('CHEMBL187460', 'C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C', 'active', '800.0'), ('CHEMBL363535', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c(C)cccc12', 'intermediate', '8800.0'), ('CHEMBL227075', 'Cc1cccc2c3c(ccc12)C1=C(C(=O)C3=O)[C@@H](C)CO1', 'intermediate', '4900.0'), ('CHEMBL45830', 'CC(C)C1=Cc2ccc3c(c2C(=O)C1=O)CCCC3(C)C', 'inactive', '30000.0'), ('CHEMBL215254', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)CO', 'inactive', '52000.0'), ('CHEMBL187460', 'C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C', 'inactive', '87600.0'), ('CHEMBL363535', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c(C)cccc12', 'active', '700.0'), ('CHEMBL227075', 'Cc1cccc2c3c(ccc12)C1=C(C(=O)C3=O)[C@@H](C)CO1', 'intermediate', '1200.0'), ('CHEMBL45830', 'CC(C)C1=Cc2ccc3c(c2C(=O)C1=O)CCCC3(C)C', 'inactive', '60200.0'), ('CHEMBL187266', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)C', 'inactive', '17100.0'), ('CHEMBL215254', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c1CCCC2(C)CO', 'inactive', '18000.0'), ('CHEMBL2146517', 'COC(=O)[C@@]1(C)CCCc2c1ccc1c2C(=O)C(=O)c2c(C)coc2-1', 'inactive', '10600.0'), ('CHEMBL187460', 'C[C@H]1COC2=C1C(=O)C(=O)c1c2ccc2c1CCCC2(C)C', 'inactive', '10100.0'), ('CHEMBL363535', 'Cc1coc2c1C(=O)C(=O)c1c-2ccc2c(C)cccc12', 'inactive', '11500.0'), ('CHEMBL227075', 'Cc1cccc2c3c(ccc12)C1=C(C(=O)C3=O)[C@@H](C)CO1', 'inactive', '10700.0'), ('CHEMBL45830', 'CC(C)C1=Cc2ccc3c(c2C(=O)C1=O)CCCC3(C)C', 'inactive', '78900.0'), ('CHEMBL18786', 'CN(C)CCCSc1ccccc1NC(=O)/C=C/c1ccccc1', 'intermediate', '5000.0'), ('CHEMBL2311740', 'CC(C)(C)NC(=O)[C@@H](c1cccnc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1', 'intermediate', '1500.0'), ('CHEMBL2311736', 'CC(C)(C)NC(=O)C(c1cc[nH]n1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1', 'active', '300.0'), ('CHEMBL2311734', 'CC(C)(C)NC(=O)C(c1ccccn1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1', 'active', '300.0'), ('CHEMBL2311733', 'CC(C)(C)NC(=O)C(c1ccncc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1', 'inactive', '45000.0'), ('CHEMBL2311732', 'Cc1ccc(C(C(=O)NC(C)(C)C)N(C(=O)c2ccco2)c2ccc(C(C)(C)C)cc2)cn1', 'active', '300.0'), ('CHEMBL2311731', 'CC(C)(C)NC(=O)C(c1cnccn1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1', 'intermediate', '5500.0'), ('CHEMBL2311730', 'CC(C)(C)NC(=O)C(c1ccnnc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1', 'inactive', '10000.0'), ('CHEMBL2311729', 'Cn1cnc(C(=O)N(c2ccc(C(C)(C)C)cc2)C(C(=O)NC(C)(C)C)c2cccnc2)c1', 'inactive', '75000.0'), ('CHEMBL2311727', 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1ccc(Cl)o1)c1ccc(C(C)(C)C)cc1', 'intermediate', '5200.0'), ('CHEMBL2311726', 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1ncco1)c1ccc(C(C)(C)C)cc1', 'inactive', '47000.0'), ('CHEMBL2311709', 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)C1=NC=NC1)c1ccc(C(C)(C)C)cc1', 'intermediate', '6000.0'), ('CHEMBL2311705', 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1cccs1)c1ccc(C(C)(C)C)cc1', 'inactive', '50000.0'), ('CHEMBL2311700', 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1cnco1)c1ccc(C(C)(C)C)cc1', 'inactive', '39000.0'), ('CHEMBL2311695', 'CC(C)c1ccc(N(C(=O)c2ccco2)C(C(=O)NC(C)(C)C)c2cccnc2)cc1', 'inactive', '28100.0'), ('CHEMBL2311694', 'CC(C)(C)NC(=O)C(c1cccnc1)N(C(=O)c1ccco1)c1ccc(C(C)(C)C)cc1', 'intermediate', '4800.0'), ('CHEMBL1405735', 'CCC(C)c1ccc(N(C(=O)c2ccco2)C(C(=O)NC2CCCC2)c2cccnc2)cc1', 'intermediate', '2200.0'), ('CHEMBL2311693', 'C=C(Cc1cccc(C)c1)C1=CC=C(c2ccc(C)cc2)C1', 'inactive', '13000.0'), ('CHEMBL2311692', 'O=C(Oc1cncc(Br)c1)c1cccs1', 'active', '500.0'), ('CHEMBL2311691', 'CCN(CC)c1ccc(C(=O)On2nnc3ccccc32)cc1', 'inactive', '11100.0'), ('CHEMBL2397338', 'CC(C)C[C@@H]1NC(=O)[C@@H](NC(=O)OCc2ccccc2)Cc2cn(nn2)CCCNC(=O)CC[C@@H](C=O)NC1=O', 'inactive', '15500.0'), ('CHEMBL2402686', 'COc1ccccc1NCC(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)c1nc2ccccc2s1', 'inactive', '14000.0'), ('CHEMBL2402685', 'COc1cccc(NCC(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]2CCNC2=O)C(=O)c2nc3ccccc3s2)c1', 'inactive', '10000.0'), ('CHEMBL2402680', 'CC(C)C[C@H](NC(=O)COc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)c1nc2ccccc2s1', 'inactive', '24000.0'), ('CHEMBL2402508', 'COc1ccc(CC(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](C[C@@H]2CCNC2=O)C(=O)c2nc3ccccc3s2)cc1', 'inactive', '43000.0'), ('CHEMBL2402501', 'CC(C)C[C@H](NC(=O)OCc1ccccc1)C(=O)N[C@@H](C[C@@H]1CCNC1=O)C(=O)c1nc2ccccc2s1', 'inactive', '21000.0'), ('CHEMBL18786', 'CN(C)CCCSc1ccccc1NC(=O)/C=C/c1ccccc1', 'inactive', '323000.0'), ('CHEMBL1929019', 'CC(=O)N[C@@H](CO)C(=O)N[C@@H](C)C(=O)N[C@H](C(=O)N[C@@H](CC1CCCCC1)C(=O)N[C@H](C=O)Cc1c[nH]cn1)C(C)C', 'active', '65.0'), ('CHEMBL2402692', 'COC(=O)/C=C/[C@H](C[C@@H]1CCNC1=O)NC(=O)[C@H](CC(C)C)NC(=O)[C@@H](NC(=O)OCc1ccccc1)C(C)C', 'intermediate', '9100.0'), ('CHEMBL2402691', 'CC(=O)N[C@H](C(=O)N[C@H](C(=O)N[C@@H](CC(C)C)C(=O)N[C@@H](CCC(=O)N(C)C)C(=O)Cn1[nH]c(=O)c2c([N+](=O)[O-])cccc2c1=O)[C@H](C)OCc1ccccc1)C(C)C', 'active', '600.0'), ('CHEMBL406516', 'CC(C)C[C@H](NC(=O)[C@@H](NC(=O)[C@H](C)NC(=O)OCc1ccccc1)C(C)C)C(=O)NC(Cc1ccccc1)C(=O)C(F)(F)F', 'inactive', '10000.0'), ('CHEMBL2442082', 'CCC(C)(C)NC(=O)[C@@H](c1ccn(C)c1)N(C(=O)Cn1nnc2ccccc21)c1ccc(NC(C)=O)cc1', 'intermediate', '6200.0'), 

In [ ]:
df3

    molecule_chembl_id  ... standard_value
0         CHEMBL187579  ...         7200.0
1         CHEMBL188487  ...         9400.0
2         CHEMBL185698  ...        13500.0
3         CHEMBL426082  ...        13110.0
4         CHEMBL187717  ...         2000.0
..                 ...  ...            ...
128      CHEMBL2146517  ...        10600.0
129       CHEMBL187460  ...        10100.0
130       CHEMBL363535  ...        11500.0
131       CHEMBL227075  ...        10700.0
132        CHEMBL45830  ...        78900.0

[133 rows x 4 columns]

### **Alternative method**

In [ ]:
selection = ['molecule_chembl_id', 'canonical_smiles', 'standard_value']
df3 = df2[selection]
df3

    molecule_chembl_id  ... standard_value
0         CHEMBL187579  ...         7200.0
1         CHEMBL188487  ...         9400.0
2         CHEMBL185698  ...        13500.0
3         CHEMBL426082  ...        13110.0
4         CHEMBL187717  ...         2000.0
..                 ...  ...            ...
128      CHEMBL2146517  ...        10600.0
129       CHEMBL187460  ...        10100.0
130       CHEMBL363535  ...        11500.0
131       CHEMBL227075  ...        10700.0
132        CHEMBL45830  ...        78900.0

[133 rows x 3 columns]

In [ ]:
pd.concat([df3,pd.Series(bioactivity_class)], axis=1)

    molecule_chembl_id  ...             0
0         CHEMBL187579  ...  intermediate
1         CHEMBL188487  ...  intermediate
2         CHEMBL185698  ...      inactive
3         CHEMBL426082  ...      inactive
4         CHEMBL187717  ...  intermediate
..                 ...  ...           ...
128      CHEMBL2146517  ...      inactive
129       CHEMBL187460  ...      inactive
130       CHEMBL363535  ...      inactive
131       CHEMBL227075  ...      inactive
132        CHEMBL45830  ...      inactive

[133 rows x 5 columns]

Saves dataframe to CSV file

In [45]:
df3.to_csv('bioactivity_preprocessed_data.csv', index=False)

In [46]:
! ls -l

total 188
-rw-r--r-- 1 root root 156586 Sep 10 04:15 bioactivity_data.csv
-rw-r--r-- 1 root root  22604 Sep 10 05:07 bioactivity_preprocessed_data.csv
drwx------ 5 root root   4096 Sep 10 04:18 gdrive
drwxr-xr-x 1 root root   4096 Sep  4 13:25 sample_data

Let's copy to the Google Drive

In [48]:
! cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [ ]:
! ls "/content/gdrive/My Drive/Colab Notebooks/data"

bioactivity_data.csv  bioactivity_preprocessed_data.csv

---